name: pangeo-climpred
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake-esm
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - pip
  # regridding
  - esmpy
  - xesmf
  - cartopy # mapping
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/bradyrx/climpred.git
    - jupyter-server-proxy # dashboard communication
    - nb_black # linting
    - git+https://github.com/bradyrx/esmtools.git # for FDR
